name: admin_dashboard
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  adaptive_scrollbar: ^2.1.2
  awesome_dialog: ^3.0.2
  bcrypt: ^1.1.3
  bloc: ^8.1.4
  cached_network_image: ^3.3.1
  cloud_firestore: ^5.0.0
  cloud_firestore_web: ^4.0.0
  cupertino_icons: ^1.0.2
  date_format: ^2.0.7
  dio: ^5.5.0+1
  envied: ^0.5.4+1
  excel: ^4.0.6
  firebase_auth: ^5.1.4
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.2
  firebase_storage: ^12.0.0
  firebase_vertexai: ^0.2.2
  firebaseapis: ^0.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_google_maps_webservices: ^1.1.1
  flutter_heat_map: ^1.2.1
  flutter_map: ^7.0.1
  flutter_polyline_points: ^2.0.0
  flutter_ringtone_player: ^4.0.0+3
  flutter_toastr: ^1.0.3
  fluttertoast: ^8.2.6
  geocoding: ^3.0.0
  get: ^4.6.5
  google_fonts: any
  google_maps_flutter: ^2.6.1
  google_maps_flutter_web: ^0.5.8
  google_places_flutter: ^2.0.9
  google_sign_in: ^6.1.0
  image: ^4.2.0
  image_network: ^2.5.1
  image_picker: ^1.1.2
  image_picker_web: ^4.0.0
  intl: ^0.18.0
  intl_phone_field: ^3.1.0
  location: ^7.0.0
  oktoast: ^3.4.0
  path: ^1.9.0
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.0.17
  uuid: ^4.4.0
 
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets: 
    - assets/images/

    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

#flutter_intl:
#  enabled: true
