// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyDoKgUa02_BAKM9XWnAIW-3jfQ-vDzt5Dg',
  //   appId: '1:119067449963:web:3a9d89ed1325318818ef2e',
  //   messagingSenderId: '119067449963',
  //   projectId: 'flutter-uber-clone-with-ef45b',
  //   authDomain: 'flutter-uber-clone-with-ef45b.firebaseapp.com',
  //   databaseURL: 'https://flutter-uber-clone-with-ef45b-default-rtdb.firebaseio.com',
  //   storageBucket: 'flutter-uber-clone-with-ef45b.appspot.com',
  //   measurementId: 'G-HBS2MV8Z5H',
  //  );
  // my firebase code


  static const FirebaseOptions web =FirebaseOptions(
    apiKey: "AIzaSyB8r8K7WXYEXBwHH0y4i8OYm-7k3qgOgfQ",
    authDomain: "transporter-app-59aac.firebaseapp.com",
    projectId: "transporter-app-59aac",
    storageBucket: "transporter-app-59aac.firebasestorage.app",
    messagingSenderId: "585762437257",
    appId: "1:585762437257:web:8f3f49fd6ffca38ce06e58",
    measurementId: "G-CH64HW2PYH"
);
  //  FirebaseOptions(
    
  //     apiKey: "AIzaSyC3Hht0P944IhbfYXvsonb6YQ3L8raFKyQ",
  //     appId: '1:903685333939:web:f3f31edd3306f06fc621c6',
  //     messagingSenderId: '903685333939',
  //     projectId: 'ghayti-app-af906',
  //     authDomain: 'ghayti-app-af906.firebaseapp.com',
  //     storageBucket: 'ghayti-app-af906.appspot.com',
  //     measurementId: "G-HW1K0QJR47");
}
